# Generated by Django 4.1.1 on 2024-04-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('has_basket', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'P'), ('ready', 'R')], default='pending', max_length=7)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.bike')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='frame_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.frame'),
        ),
        migrations.AddField(
            model_name='bike',
            name='seat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.seat'),
        ),
        migrations.AddField(
            model_name='bike',
            name='tire_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tire'),
        ),
    ]
