# Generated by Django 4.1.1 on 2024-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='frame_id',
            new_name='frame',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='seat_id',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='tire_id',
            new_name='tire',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Ready')], default='P', max_length=7),
        ),
    ]
