# Generated by Django 4.1.1 on 2024-05-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_frame_id_bike_frame_rename_seat_id_bike_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
